name: Sync Fork

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync develop
        run: gh repo sync ${{ github.repository }} --branch develop
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
